### ISSUE TITLE
Problem mit "Innen- und Außendienst"

### ISSUE THREAD

**Issue by Markus-Schadegg** [motsiw/rggl#5]
Hallo,

es gibt ein Problem mit "Auslieferung im Innen- und Außendienst"
das Plugin korrigiert dies zu "Auslieferung im en- und Außendienst".

Gruß

Markus

**Comment by Markus-Schadegg** [comment]
P.S. Github hat gerade Probleme mit dem Upload von JPGs... sonst hätte ich auch Screenshots angehängt.

**Comment by motsiw** [comment]
Danke für den Hinweis. In 6.1.5 gefixt (für Firefox bereits online, für Chrome eingereicht).
